spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8 # change this to your own jdbc url
    username: test  # change this to your own username (avoid using a superuser)
    password: Jianuo123?  # change this to your own password
    hikari:
      auto-commit: false
logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
